### ISSUE TITLE
Reporte 

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Azucena-Tejeda#2]
[reporte de texbox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Azucena-Tejeda/files/6338284/reporte.de.texbox.pdf)

**Comment by IsaHuerta23** [comment]
Calificación: 18/20

**Comment by josealfredo79** [comment]
esta bien hecho y revisado
